apiVersion: v1
kind: Service
metadata:
  name: hello-world-arun-service
spec:
  selector:
    app: hello-world-arun
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
    nodePort: 30000
